#WAP TO FIND THAT GIVEN NUMBER IS MULTIPLE OF 7 OR NOT;
num=int(input("ENTER YOUR NUMBER:"))
if(num%7==0):
    print("YSS IT IS MULTIPLE OF 7!!!!")
else:
    print("TRY OTHER NUMBER NOT MULTIPLE OF 7!!!")
    